=== SergioValera33/EjerciciosLMSGI/batman.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT  batman (personajes)>
<!ELEMENT  personajes (personaje)+ >
<!ELEMENT  personaje (nombreReal, edad, (heroe | villano)) >
<!ELEMENT  nombreReal (#PCDATA)>
<!ELEMENT  edad (#PCDATA | fechaNacimiento)*>
<!ELEMENT fechaNacimiento (#PCDATA) >
<!ELEMENT  heroe EMPTY>
<!ELEMENT  villano EMPTY>
<!ATTLIST personaje nombre ( batman | robin | joker | pingÃ¼ino | harley) "batman"
                    colorTraje  CDATA #IMPLIED 
                    altura CDATA #REQUIRED
                    ciudad CDATA  #FIXED "Gotham city"
                    codigo ID #REQUIRED
                    codigoDeEnemigoPrincipal IDREF #IMPLIED>

=== SergioValera33/EjerciciosLMSGI/batman.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE batman SYSTEM "batman.dtd">
<batman>
    <personajes>
        <personaje nombre = "batman"  codigo = " bat" codigoDeEnemigoPrincipal = "joker"coloTraje= "Negro" altura = " 1.90">
            <nombreReal> Bruce Wayne</nombreReal>
            <edad> 40
            <fechaNacimiento>3/10/1983 </fechaNacimiento>
            </edad>
            <heroe/>     
        </personaje>
        <personaje nombre = "harley" codido = "har"altura = "1.78" ciudad = "Gotham City">
            <nombreReal>Doctora psic√≥loga</nombreReal>
            <edad> 32
                <fechaNacimiento>3/10 /1991</fechaNacimiento>
            </edad>
            <villano/>     
        </personaje>
        <personaje nombre = "joker" codido = "jok"altura = "1.85" ciudad = "Gotham City">
            <nombreReal>Mafiosillo</nombreReal>
            <edad> 57
                <fechaNacimiento>3/10 /1966</fechaNacimiento>
            </edad>
            <villano/>     
        </personaje>
    </personajes>
</batman>
