=== SergioValera33/EjerciciosLMSGI/cocteleria.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cocteleria (cocteles, ofertas)>
<!ELEMENT cocteles (coctel+)>
<!ELEMENT ofertas (oferta*)>
<!ELEMENT coctel (nombre, propiacreacion?, precio, (existencias | agotado))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT propiacreacion EMPTY>
<!ELEMENT precio EMPTY>
<!ELEMENT existencias EMPTY>
<!ELEMENT agotado EMPTY>
<!ELEMENT oferta (#PCDATA | coctelReferido)*>
<!ELEMENT coctelReferido ANY>
<!ATTLIST cocteleria direccion CDATA #IMPLIED 
                      nombre CDATA #REQUIRED
                      telefono CDATA #FIXED "675420174">
<!ATTLIST coctel codigo ID #REQUIRED
                bebidaPrincipal (vodka | larios | martini) "vodka">
<!ENTITY % atributoCoste "coste CDATA #IMPLIED"> 
<!ATTLIST precio %atributoCoste;>
<!ATTLIST oferta %atributoCoste;>

=== SergioValera33/EjerciciosLMSGI/cocteleria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cocteleria SYSTEM "cocteleria.dtd">
<cocteleria direccion="C. Goya, 8, 14006 Córdoba" nombre="Distrito Cocktail Bar" telefono="675420174">
    <cocteles>
        <coctel codigo="nariz" bebidaPrincipal="vodka">
            <nombre> Gato cósmico</nombre>
            <propiacreacion/>
            <precio coste="7.5" />
            <existencias />
        </coctel>
        <coctel codigo="ench">
            <nombre>Rudolph </nombre>
            <precio coste="8" />
            <agotado />
        </coctel>
    </cocteles>
    <ofertas>
        <oferta coste="18">2x1 
        </oferta>
    </ofertas>
</cocteleria>
